"""empty message

Revision ID: c3f7997d9050
Revises: aa01fc72001a
Create Date: 2023-06-10 18:00:41.894838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3f7997d9050'
down_revision = 'aa01fc72001a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appeal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeal',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.TEXT(), nullable=False),
    sa.Column('last_name', mysql.TEXT(), nullable=True),
    sa.Column('surname', mysql.TEXT(), nullable=True),
    sa.Column('student_group', mysql.TEXT(), nullable=True),
    sa.Column('contact', mysql.TEXT(), nullable=False),
    sa.Column('theme', mysql.TEXT(), nullable=False),
    sa.Column('full_text', mysql.TEXT(), nullable=False),
    sa.Column('date_appeal', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
